### PR TITLE
Custom object factory usage documentation

### PR DESCRIPTION
**Pull request by ralphkar**
## Summary

A separate README.md has bee added to the core package that described the details of DI when using a custom object factory and how to do this.

(as requested in #1710)

### CODE REVIEW

**Comment by mpkorstanje** [comment]
This is really good. More then I expected. This would be a good fix for:

https://github.com/cucumber/docs.cucumber.io/issues/362

**Comment by ralphkar** [comment]
So what is it that you recommend? Merge the PR? Or should create a new PR for that other issue? I am not sure what the process is.

**Comment by ralphkar** [comment]
Ok, I had a look at the documentation project and I have no clue of where and how this could be integrated or how this relates to the mentioned issue.
I have created the content, but as long as I don't know how to integrate it into the documentation I will not create a new PR.

**Comment by mpkorstanje** [comment]
That is okay! I'm not sure why I closed this PR. Must have fat-fingered it.

**Comment by mpkorstanje** [comment]
Continued in https://github.com/cucumber/docs.cucumber.io/pull/369

**Pull request closed without merging**
