### PR TITLE
Demonstration for https://github.com/cucumber/cucumber-jvm/issues/915

### PR DESCRIPTION
**Pull request by albers**
DO NOT MERGE. This PR serves to illustrate #915.

Without this PR, all CDI related items are located in `src/test`. `mvn -pl weld clean test` (issued from the project root after a successful local build) succeeds.

With this PR, `beans.xml` and `Belly` are located in `src/main/{java,resources}` whereas the injection point `BellyStepdefs` is located in `src/test/java`. `mvn -pl weld clean test` now fails with:

    org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001308: Unable to resolve any beans for Type: class cucumber.runtime.java.weld.BellyStepdefs; Qualifiers: [@javax.enterprise.inject.Any()]
            at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:101)
            at cucumber.runtime.java.weld.WeldFactory.getInstance(WeldFactory.java:52)
            at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
            at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
            at cucumber.runtime.Runtime.runStep(Runtime.java:299)
    [...]

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
@albers do you intend to complete this PR so the build passes?

**Comment by albers** [comment]
@aslakhellesoy Sorry, I do not have the required knowledge to do so.
So all I can do in this place is to provide a working demo of the issue.

**Comment by brasmusson** [comment]
@albers You need to have a `beans.xml` both in `src/test/resources/META-INF/` and in ` src/main/resources/META-INF/, then it works.

**Comment by aslakhellesoy** [comment]
Can we close this and #915 now please?

**Comment by albers** [comment]
Please wait until I verified this.

**Comment by albers** [comment]
@brasmusson Thanks very much for your support. This was indeed the solution, both for the problem outlined in this PR and for my actual project.

**Pull request closed without merging**
