### PR TITLE
Add @BeforeStep and @AfterStep annotations.

### PR DESCRIPTION
**Pull request by Evg3n**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
There seems to be a lot of duplication. That means more maintenance. Can you refactor to remove some more of it please?

**Comment by Evg3n** [comment]
Will do my best.

**Comment by Evg3n** [comment]
Hi @aslakhellesoy,

Do you treat  
    void addBeforeStepHook(StepHookDefinition hookDefinition);
    void addAfterStepHook(StepHookDefinition hookDefinition);
as duplicates of 
    void addBeforeHook(HookDefinition hookDefinition);
    void addAfterHook(HookDefinition hookDefinition);?
Or i can leave them as is?

**Comment by Evg3n** [comment]
Hello @aslakhellesoy 

Could you please answer my question so I can fix/leave as is and push my code.

Best regards,
Eugene.

**Comment by Evg3n** [comment]
@aslakhellesoy look at updated pull request.

**Comment by p1um** [comment]
Hello Evg3n.

Are you going to finish your pull request? I really need in my project. If this is imposible for you. Can i finish your pull request?

Best regards,
Kirill.

**Comment by BevanR** [comment]
Please update the status of this.  We would also need this feature.

**Comment by Evg3n** [comment]
Hello guys,

Implementation is done and waiting a review from @aslakhellesoy. He had some comments so I fixed issues.

PS: I need this feature badly as well.

Best regards,
Eugene.

**Comment by vsethupandian** [comment]
@aslakhellesoy  has this feature been implemented?

**Comment by sahajamit** [comment]
@aslakhellesoy Any update on this pull request?

**Comment by aslakhellesoy** [comment]
Sorry to keep you waiting. We'll hold off on this until we're on Gherkin3, which is a big chunk of work.

**Comment by kirillzh** [comment]
@Evg3, If I embed file in `@AfterStep` hook, file is getting embedded in the next step.

**Comment by kmelderis** [comment]
This is a **must have** feature partially due to real life situation like this:
http://stackoverflow.com/questions/7286254/cucumber-wait-for-ajaxsuccess

AfterStep('@javascript') 
do
  begin
    When 'I wait for the ajax request to finish'
  rescue
  end
end

Just to serve an example how useful @AfterStep hook would be for us CucumberJVM users.

**Comment by BhuvaneshMani** [comment]
Need of BeforeStep and AfterStep hooks very badly. It provides loads of benefits for everyone and managing tests will be become easy. Please release it soon..

**Comment by sachingsachin** [comment]
Not seen the pull request in detail. But please add the ability to log messages in StepDefinitions.java by adding methods with the new annotations.
Helpful for situations like http://stackoverflow.com/questions/39800566/print-cucumber-scenario-and-step-before-it-is-executed-on-the-console and http://stackoverflow.com/questions/39664422/in-cucumber-is-it-possible-to-programmatically-get-the-current-step-being-execu

**Comment by michalkaftanski-airhelp** [comment]
Hello @Evg3n,
are you going to merge this hooks into master?

**Comment by kirillzh** [comment]
@BhuvaneshMani it's on my [fork](https://github.com/kirillzh/cucumber-jvm)

**Comment by BhuvaneshMani** [comment]
@kirillzh When can i expect the push of your fork into master? Awaiting for the feature :+1:

**Comment by kirillzh** [comment]
@BhuvaneshMani sorry, it is not up to me. All I did is created fork and merge couple of already existing PRs.

**Comment by swordmaster2k** [comment]
+1 would be helpful if this was merged

**Comment by angelyangw** [comment]
+1 want this

**Comment by rommy1204** [comment]
+, we need that too

**Comment by JMVM** [comment]
+1

**Comment by mihaibuba** [comment]
+1

**Comment by G0dwin** [comment]
+1

**Comment by mpkorstanje** [comment]
Superseded by #938.

**Pull request closed without merging**
