### PR TITLE
Custom predicate

### PR DESCRIPTION
**Pull request by raulmiraoliver**
**Is your pull request related to a problem? Please describe.**

https://community.smartbear.com/t5/Cucumber-Open/Custom-filters/td-p/213203
My team needs a way to have scenarios filtered in a more customizable way than static tagging. This allows setting new Pickle filters.

**Describe the solution you have implemented**
Created a new config called customPredicate that can be set to a Predicate<Pickle> to filter out scenarios.

### CODE REVIEW

**Comment by raulmiraoliver** [comment]
Getting
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.13.2:check (check) on project cucumber-junit: The following API problems caused the build to fail:
[ERROR] java.class.externalClassExposedInAPI: interface io.cucumber.core.gherkin.Argument: A class from supplementary archives is used in a public capacity in the API. [io.cucumber:cucumber-gherkin:jar:6.10.1-SNAPSHOT]
[ERROR] java.class.externalClassExposedInAPI: interface io.cucumber.core.gherkin.Pickle: A class from supplementary archives is used in a public capacity in the API. [io.cucumber:cucumber-gherkin:jar:6.10.1-SNAPSHOT]
[ERROR] java.class.externalClassExposedInAPI: interface io.cucumber.core.gherkin.Step: A class from supplementary archives is used in a public capacity in the API. [io.cucumber:cucumber-gherkin:jar:6.10.1-SNAPSHOT]
[ERROR] java.class.externalClassExposedInAPI: enum io.cucumber.core.gherkin.StepType: A class from supplementary archives is used in a public capacity in the API. [io.cucumber:cucumber-gherkin:jar:6.10.1-SNAPSHOT]
[ERROR] java.class.externalClassExposedInAPI: class io.cucumber.plugin.event.Location: A class from supplementary archives is used in a public capacity in the API. [io.cucumber:cucumber-plugin:jar:6.10.1-SNAPSHOT]
```

Please let me know if the PR has any future so I invest time on creating classes for the API to detach it from the supplementary archives.

**Comment by mpkorstanje** [comment]
There several ways to achieve this using the frameworks Cucumber integrates with:

* If you are using TestNG I would suggest filtering the scenario in the `@DataProvider` annotated method.

 * If you are using JUnit 5 I would suggest using the JUnit platform in combination with the [Cucumber JUnit Platform Engine](https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine). That way the [JUnit Platform Launcher ](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/module-summary.html) will allow you to use a [`PostDiscoveryFilter`](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/PostDiscoveryFilter.html). This should allow you to dynamically filter on tags and names. The `PostDiscoveryFilter` can be discovered via SPI so should be enabled by default if used that way.

    Note that JUnit Platform is not a feature complete replacement for JUnit 4 yet. If you using multiple runners (suites) you'll be waiting for the release of https://github.com/junit-team/junit5/pull/2416 and if you need before/after all hooks you'll be waiting for https://github.com/cucumber/cucumber-jvm/pull/1876.

So 'm not sure if it is worth the additional complexity of integrating this with the core.

**Comment by raulmiraoliver** [comment]
@mpkorstanje, I understand - thank you for your comment! I'll discuss with the team whether it's worth in our case to upgrade to JUnit 5, as that seems to be the most fit option.

Even if we do so, if you see any value in this PR I'm willing to invest some time on it. If not, please just say/feel free to close it.

Thanks!

**Comment by mpkorstanje** [comment]
The offer is appreciated. Though as it stands the use case is somewhat of a niche.

Additionally loading classes by name through the CLI is something I'd like to replace with SPI (https://github.com/cucumber/cucumber-jvm/issues/1834) in the long term and possibly through a public API for running Cucumber (https://github.com/cucumber/cucumber-jvm/issues/1711).

**Pull request closed without merging**
