### PR TITLE
Print supported languages details

### PR DESCRIPTION
**Pull request by tsundberg**
## Summary

I updated the language list to include not just the language code but also the language name in English as well as the native language name.

## Details

The list of languages looked like this:

```
af
am
ar
ast
az
bg
…
```

There are 72 languages supported. It isn't easy to know which language is which.

I extended the list to look like this:

```
af              Afrikaans                 Afrikaans                   
am              Armenian                  հայերեն                     
ar              Arabic                    العربية                     
ast             Asturian                  asturianu                   
az              Azerbaijani               Azərbaycanca                
bg              Bulgarian                 български                   
…
```

## Motivation and Context

This will make it easier to understand what language a language code is supporting.

## How Has This Been Tested?

I added unit tests for calculating the maximum width for each column.
I used inspection to see that the printout looks nice.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [X] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tsundberg** [comment]
The build fails, the dependency io.cucumber:gherkin:jar:5.0.1-SNAPSHOT is not available.

The error message is this: 

`[ERROR] Failed to execute goal on project cucumber-core: Could not resolve dependencies for project io.cucumber:cucumber-core:jar:2.2.1-SNAPSHOT: Could not find artifact io.cucumber:gherkin:jar:5.0.1-SNAPSHOT in sonatype-snapshots`

What can be done about the missing snapshot dependency?

**Comment by mpkorstanje** [comment]
Once a release is made of the gherkin lib you can use the release version and it should be fine.

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber/pull/366#issuecomment-402849761

**Comment by mpkorstanje** [comment]
Had to do some maintenance on Gherkin v5. This resulted in the name and native name being accessible through getters.

https://github.com/cucumber/cucumber/tree/gherkin/v5.x.x

**Comment by mpkorstanje** [comment]
Cheers @tsundberg I regret that it took a while to get his done.

**Pull request merged**
