### PR TITLE
[Java/Java8] Rename scenario methods

### LINKED ISSUE #1893: Rename Scenario methods to be consistent with other Cucumber implementations
https://github.com/cucumber/cucumber/issues/897

Apply the usual deprecation strategy before removing old methods.

### PR DESCRIPTION
**Pull request by timtebeek**
## Summary

Deprecate Scenario.write ; Add Scenario.log
Deprecate Scenario.embed; Add Scenario.attach
Fixes #1893 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
You can ignore the failing semver. I'll have to increment the minor version to make it pass.

**Comment by timtebeek** [comment]
> You can ignore the failing semver. I'll have to increment the minor version to make it pass. And that means the version in the annotations are no longer correct.

Yeah I noticed that (even) a default interface method requires a minor version bump; Hadn't wanted to add that yet before we had a chance to discuss it, since version bumps on a branch give horrible merge conflicts if there's a release in between. So if you want I'll gladly update the merge request to target `5.7.0`, or leave that part to you as you see fit.

**Comment by mpkorstanje** [comment]
That makes sense. Bumping the minor version is a separate operation. It's better to keep PR atomic.

**Comment by timtebeek** [comment]
@mpkorstanje update in https://github.com/cucumber/cucumber-jvm/pull/1937/commits/4eec55e47aad0f20d5abc61eb548e4538cc5cb63 to use "5.7.0" in Deprecated annotations.

**Comment by mpkorstanje** [comment]
Cheers! Much appreciated again.

**Pull request merged**
