### PR TITLE
Update link to javadocs

### LINKED ISSUE #1074: Hosted documentation is outdated
## Summary

HTML page linked from https://github.com/cucumber/cucumber-jvm/tree/master/guice is outdated. The properties filename should be `cucumber.properties` not `cucumber-guice.properties`

Looking at it further it seems like http://cucumber.github.io/api/cucumber/jvm/javadoc/ is version 1.2.2 while the current version is 1.2.5.
## Steps to Reproduce (for bugs)

1. Go to https://github.com/cucumber/cucumber-jvm/tree/master/guice
2. Click link "Read package documentation online at cukes.info"
3. Notice it states "cucumber-guice.properties" instead of "cucumber.properties"

### PR DESCRIPTION
**Pull request by mlvandijk**
## Summary
"cucumber-guice.properties" has already been updated to "cucumber.properties" (see #913).
However, ink to cukes.info/api/cucumber/jvm/javadoc/cucumber/api/guice/package-summary.html is no longer valid, and was therefore removed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
There is no alternative source for the java doc?

**Comment by brasmusson** [comment]
AFAIK the source of http://cukes.info/api was the repo [cucumber.github.com](https://github.com/cucumber-attic/cucumber.github.com). Now when that repo is replaced by [docs.cucumber.io](https://github.com/cucumber/docs.cucumber.io), I would expect an api section somewhere in there where the generated api documentation can be put when releasing (as stated in the [release instructions](https://github.com/cucumber/cucumber-jvm/blob/master/CONTRIBUTING.md#releasing)).

**Comment by mlvandijk** [comment]
@brasmusson Location currently mentioned in the release instructions links to an obsolete repo, so I guess we do need to find a new location and then point there...

**Comment by mlvandijk** [comment]
Discussed today on Slack: New repo for apidocs will be https://github.com/cucumber/api.cucumber.io
Will update PR accordingly.

**Comment by mlvandijk** [comment]
@brasmusson @mpkorstanje Updated PR with link to new api doc repo. Fyi: I also checked all the README's in the other modules but didn't find any additional links to api docs.

**Pull request merged**
