### PR TITLE
killed android profile and moved android project to default profile

### PR DESCRIPTION
**Pull request by SierraGolf**

### CODE REVIEW

**Comment by brasmusson** [comment]
Good job. Some small comments:
The file `.travis_android_update` should be removed, it was only used from the now deleted android job on Travis.
Several of the README.md (android/README.md, examples/android/README.md, examples/android/android-test/README.md, examples/android/cukeulator-test/README.md I think) specify `-P android` or `-P android,android-examples` in `mvn` command, which now become obsolete.

**Comment by SierraGolf** [comment]
good points, I will clean that up

**Comment by SierraGolf** [comment]
@aslakhellesoy  anything against merging this PR?

**Comment by aslakhellesoy** [comment]
LGTM

**Comment by aslakhellesoy** [comment]
@SierraGolf don't forget to credit yourself (and others) in [History.md](https://github.com/cucumber/cucumber-jvm/blob/master/History.md).

**Comment by SierraGolf** [comment]
will do

**Pull request merged**
