### PR TITLE
Adding some documentation for Cucumber-Clojure

### PR DESCRIPTION
**Pull request by dorzey**
As highlighted in https://github.com/cucumber/cucumber-jvm/issues/780 there is a lack of documentation for cucumber-clojure. 

This is my attempt to start addressing that. I am neither a Cucumber nor Clojure expert; so this is based on my current working knowledge.

Feedback and corrections are welcome.

### CODE REVIEW

**Comment by dkowis** [comment]
I see no reason not to improve our documentation :D

**Comment by aslakhellesoy** [comment]
Thanks guys!

**Comment by aslakhellesoy** [comment]
I would have preferred these docs to be on https://cucumber.io.

How can we make it easier to contribute docs there instead?

And how can we make it easier to find the docs there?

**Comment by dkowis** [comment]
@aslakhellesoy Some sites have the "fork me on github" way of adding content to the site. Is this one also a statically generated site? Could probably do that, and note the docs in the various README's in the project.

**Comment by dorzey** [comment]
@aslakhellesoy - I'll try to find the time to raise a PR against https://github.com/cucumber/website

**Pull request merged**
