### PR TITLE
Updates regarding removal of several jvm languages

### LINKED ISSUE #1257: Update genapi.sh to reflect removal of Scala and JRuby
## Summary

Scala and JRuby were removed from this repo, but are still mentioned in the genapi.sh.
Should be updated accordingly.

## Current Behavior
Scala and JRuby were removed from this repo, but are still mentioned in the genapi.sh.

## Possible Solution
Update genapi.sh
See PR #1264

### PR DESCRIPTION
**Pull request by mlvandijk**
## Summary
Updates to reflect removal of several jvm languages

## Details
Remove ScalaDoc and Yardoc from genapi.sh
Remove mention of Clojure from CONTRIBUTING.md

## Motivation and Context
Several of the JVM languages (including Clojure, Scala, JRuby) were removed from this repo and moved to their own repos. However, they were still referenced in several places. Fixes #1257

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by brasmusson** [comment]
@mlvandijk Please move the `fix #1257` from the title to the pull-request description. In the title GitHub does not make it a clickable link, and it would interfere with [an update changelog script](https://github.com/cucumber/cucumber/issues/255). More importantly using [keywords for closing issues](https://help.github.com/articles/closing-issues-using-keywords/) in the pull-request description will make GitHub close these issues with the pull-request is merged.

**Comment by mlvandijk** [comment]
@brasmusson Done! Thank you for taking the time to explain.

**Comment by brasmusson** [comment]
@mlvandijk I did not see any edit of the pull-request description, so I did an edit of the "Motivation and Context" section to include `Fixes #1257`. Now if you go to #1257, you'll see a marker at the reference from this pull-request, which when hovered above says `this issue will close when pull-request #1264 is merged into the 'master' branch`

**Comment by mlvandijk** [comment]
Thanks again @brasmusson!

**Comment by mlvandijk** [comment]
It says here that the Travis CI build could not complete. It did fail before, so I restarted it. When I go to details now, all builds have passed... Not sure why it still says it's failed here.

**Comment by mpkorstanje** [comment]
@mlvandijk the build failed because the last step was canceled.

**Pull request merged**
