### PR TITLE
993 add picocontainer lifecycle

### PR DESCRIPTION
**Pull request by RichardBradley**
Fix for item 3 discussed at #993

Includes #992

### CODE REVIEW

**Comment by dkowis** [comment]
Could you add some tests that take advantage of the lifecycle functionality that you turned on?

**Comment by RichardBradley** [comment]
Sure, have done.

**Comment by dkowis** [comment]
Merged at f2bb89b8403d1d8e201c0d174a7a903f0efcc23f , Not sure why github isn't marking it as merged....

**Comment by dkowis** [comment]
merged as of c0ffacd7bc1a6fa6e91fab38d67ee483c43ea0da

**Comment by RichardBradley** [comment]
> Not sure why github isn't marking it as merged....

I think GitHub is right that you haven't actually merged these changes into master (or perhaps someone else undid your merge?)

If you look at the current head of master, 8d02a4fc, you'll see the branches which contain that commit listed on the left hand side: "`master`".

If you look at the commit you linked to, c0ffacd, you'll see no branches listed on the left hand side, because no live branches contain that commit. I can't fetch it with a `git fetch` either. It looks like you've since done a force-push or similar which orphaned that commit?

**Comment by dkowis** [comment]
Hrm, I didn't do a force push, I literally followed the merge from the command line commands...

Lemme try it again

**Comment by dkowis** [comment]
```
$ git merge --no-ff RichardBradley-993-add-picocontainer-lifecycle
Already up-to-date.
```

Yeah I don't get it, this is really strange. I'll just hit the Merge pull request button and then maybe that's it..

**Comment by dkowis** [comment]
AW jeez
I merged it into MY Fork of cucumber-jvm
herp all the derps

**Comment by dkowis** [comment]
There we go, merged with attribution, sorry about that: https://github.com/cucumber/cucumber-jvm/commit/19e8f3560855aaed6c8fd912fe3d5a009312fec7

**Comment by RichardBradley** [comment]
Thanks!

**Pull request merged**
