### PR TITLE
[Junit] update to Gherkin5. -- review nit picks

### PR DESCRIPTION
**Pull request by mpkorstanje**

### CODE REVIEW

**Comment by mattwynne** [comment]
@aslakhellesoy and I tried to review this today but found some failing tests in the pretty formatter.

We realised that for some reason, travis hasn't built this branch. Can you try pushing to it again (you could use `git commit --allow-empty`) and see if it triggers a build? Do all the tests definitely pass for you locally?

**Comment by mpkorstanje** [comment]
You guys are moving a bit faster then expected! The review process was not nearly as linear as it appears here.

**Comment by aslakhellesoy** [comment]
You're just used to our snail pace :-) We're doing what we can to be more regularly involved and more responsive!

**Comment by mpkorstanje** [comment]
Build is passing locally. 

I'm thinking travis is not picking this up because this is not a PR against master but against use-gherkin4.

**Comment by mattwynne** [comment]
Aha, yeah. Since that branch has now been merged you might need to open a new PR.

**Comment by mpkorstanje** [comment]
No problem. Need to start working against cucumber-jvm repo anyway.

**Pull request closed without merging**
