### PR TITLE
#1706 - WIP - add feature retries

### PR DESCRIPTION
**Pull request by nddipiazza**
## Summary

Add a retry feature.

## Details

Should be able to retry using a --retry parameter, or a Retry annotation.

## Motivation and Context

https://github.com/cucumber/cucumber-jvm/issues/1706

## How Has This Been Tested?

Pending test coverage.

## Types of changes

- [x] New feature (non-breaking change which adds functionality).

## Checklist:

- [ ] I've added tests for my code. TODO
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. TODO

### CODE REVIEW

**Comment by mpkorstanje** [comment]
I appreciate that you're creating a PR for a new feature. However we request that you open an issues to discuss significant contributions prior to making them.

This would have allowed me to point out that the reason `IRetryListener` doesn't work in TestNG due to https://github.com/cbeust/testng/issues/891. And I would prefer that you work on fixing this issue rather then build it into the TestNG and JUNit integrations.

Additionally Cucumber-JVM currently doesn't support reporting on retried tests at all. So merely adding functionality to rerun tests until passed will not be sufficient to accept a PR. There is functionality coming up to make this possible but that won't be available the new Message protocol has been implemented (#1841).

**Comment by nddipiazza** [comment]
Cool your final comment will be sufficient for my purposes. 
I will work on https://github.com/cbeust/testng/issues/891 as time allows.
I'll also keep an eye on https://github.com/cucumber/cucumber-jvm/pull/1841

**Comment by nddipiazza** [comment]
> Finally it would also have allowed me to point out that if you are using TestNG and aren't interested in fixing cbeust/testng#891 nor willing to wait for #1841 you can also extend AbstractTestNGCucumberTests and invoke runScenario until the tests passes.

@mpkorstanje question for you about this comment... let's say I do what you suggested here and then it passes on the 2nd+ try. Will the cucumber-report have a single successful attempt? or will the cucumber-report get messed up?

**Comment by mpkorstanje** [comment]
I honestly I don't know. It will very much depend on the way a particular reporting plugin was written. However given that currently there is no way to differentiate between the events from the original execution and the events from any subsequent rerun, I suspect it won't go well.

**Comment by nddipiazza** [comment]
@mpkorstanje  I'm currently using https://mvnrepository.com/artifact/net.masterthought/cucumber-reporting/4.11.2

What I can try to do if necessary is run test, some errors occur. we then parse the testng test output and initiate retry loop where appropriate. and if the test passes, inject the cucumber output with the passing test to replace the previously failing test and regenerate the report html. Meh?

**Comment by mpkorstanje** [comment]
Ideally your reporter would understand that a test was rerun and report it as such. Currently only the native TestNG and JUnit reporters can do that. So you'd have to rely on those reports rather then anything generated by Cucumber or based on Cucumbers output.

So if you ask me what you can try: I'd spend my time making tests more stable.

**Comment by nddipiazza** [comment]
> I'd spend my time making tests more stable.

this is the classic response to the flaky test retry situation. and in my case, there is a mainframe system that causes intermittent test failures completely outside of my control.

**Comment by mpkorstanje** [comment]
Been there done that.

https://github.com/cucumber/cucumber-jvm/issues/1120

In hindsight it was the biggest waste of my time. 😁

**Comment by nddipiazza** [comment]
@mpkorstanje this works great. I noticed that it still has a json record of the failures prior to the passing retry however. Is there some way to "erase" the previous failed attempts prior to letting the scenario pass? I am looking into the source code of the cucumber-reporting github project as well to see if I can do this during the generation of the pretty HTML report.

**Comment by nddipiazza** [comment]
@mpkorstanje  never mind my previous question. i went ahead and added this ability into the cucumber-reporting in a PR. 
see 
https://github.com/damianszczepanik/cucumber-reporting/pull/914

**Comment by mpkorstanje** [comment]
Ooh. Well done.

**Pull request closed without merging**
