### PR TITLE
add a exception in to pending exception as the org.junit.internal. is…

### PR DESCRIPTION
**Pull request by nablik**
as org.junit.internal.AssumptionViolatedException is depercated, I added the new line in the PENDING_EXCEPTION array [org.junit.AssumptionViolatedException]

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Could you add a test to `RuntimeTest` please?

**Comment by nablik** [comment]
Hi Aslak,
No itis impossible to write unit test now.
The reason is the CucumberCore use the Junit version 4.11
and the PR  is to cover the Junit 4.12.
And upgrading to 4.12 will breaks Android.
So I am bit in tricky situation.

Is there any other way to import 4.12?
in that case I can push the test.

regards,
Karim,

**Comment by aslakhellesoy** [comment]
@nablik I just upgraded to JUnit 4.12. Could you add it now please?

**Comment by nablik** [comment]
Done Sir :)

**Comment by dkowis** [comment]
It's got some conflicts now. @nablik could you check to see if this is still legit?

**Comment by nablik** [comment]
Sorry guys, I lost momentum, @David, which kind of conflict it has ?
in case of upgrade to JUnit 12 I think we can get rid of
org.junit.internal.AssumptionViolatedException
that was historically causing the problem.
Regards,
Karim.

**Comment by brasmusson** [comment]
Duplicate of #961 (which is already merged).

**Pull request closed without merging**
