### PR TITLE
Fix the build

### PR DESCRIPTION
**Pull request by aslakhellesoy**
Too old, breaks the build.

### CODE REVIEW

**Comment by mattwynne** [comment]
Another example is failing:
```
 CalculatorTest.cucumber » ClassNotFound cucumber.runtime.ClassFinder not found
```

@aslakhellesoy any idea what that means?

**Comment by mpkorstanje** [comment]
The full stack showing that felix is trying find the class inside a bundle.

```
java.lang.ClassNotFoundException: cucumber.runtime.ClassFinder not found by PAXEXAM-PROBE-7dbcddc9-967d-4fd0-99c7-3d8e6809a742 [27]

	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
	at java.lang.Class.privateGetPublicMethods(Class.java:2743)
	at java.lang.Class.getMethods(Class.java:1480)
	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.findAndInvoke(JUnitProbeInvoker.java:94)
	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.call(JUnitProbeInvoker.java:73)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.call(NativeTestContainer.java:109)
	at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:84)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:264)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:98)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

So I'm gessuing these message are significant:
```
ERROR: Bundle io.cucumber.core [18] Error starting mvn:io.cucumber/cucumber-core (org.osgi.framework.BundleException: Unable to resolve io.cucumber.core [18](R 18.0): missing requirement [io.cucumber.core [18](R 18.0)] osgi.wiring.package; (osgi.wiring.package=io.cucumber.tagexpressions) Unresolved requirements: [[io.cucumber.core [18](R 18.0)] osgi.wiring.package; (osgi.wiring.package=io.cucumber.tagexpressions)])
org.osgi.framework.BundleException: Unable to resolve io.cucumber.core [18](R 18.0): missing requirement [io.cucumber.core [18](R 18.0)] osgi.wiring.package; (osgi.wiring.package=io.cucumber.tagexpressions) Unresolved requirements: [[io.cucumber.core [18](R 18.0)] osgi.wiring.package; (osgi.wiring.package=io.cucumber.tagexpressions)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
ERROR: Bundle io.cucumber.java [19] Error starting mvn:io.cucumber/cucumber-java (org.osgi.framework.BundleException: Unable to resolve io.cucumber.java [19](R 19.0): missing requirement [io.cucumber.java [19](R 19.0)] osgi.wiring.package; (&(osgi.wiring.package=cucumber.runtime)(version>=2.0.0)(!(version>=3.0.0))) [caused by: Unable to resolve io.cucumber.core [18](R 18.0): missing requirement [io.cucumber.core [18](R 18.0)] osgi.wiring.package; (osgi.wiring.package=io.cucumber.tagexpressions)] Unresolved requirements: [[io.cucumber.java [19](R 19.0)] osgi.wiring.package; (&(osgi.wiring.package=cucumber.runtime)(version>=2.0.0)(!(version>=3.0.0)))])
org.osgi.framework.BundleException: Unable to resolve io.cucumber.java [19](R 19.0): missing requirement [io.cucumber.java [19](R 19.0)] osgi.wiring.package; (&(osgi.wiring.package=cucumber.runtime)(version>=2.0.0)(!(version>=3.0.0))) [caused by: Unable to resolve io.cucumber.core [18](R 18.0): missing requirement [io.cucumber.core [18](R 18.0)] osgi.wiring.package; (osgi.wiring.package=io.cucumber.tagexpressions)] Unresolved requirements: [[io.cucumber.java [19](R 19.0)] osgi.wiring.package; (&(osgi.wiring.package=cucumber.runtime)(version>=2.0.0)(!(version>=3.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
ERROR: Bundle io.cucumber.osgi [20] Error starting mvn:io.cucumber/cucumber-osgi (org.osgi.framework.BundleException: Unable to resolve io.cucumber.osgi [20](R 20.0): missing requirement [io.cucumber.osgi [20](R 20.0)] osgi.wiring.package; (&(osgi.wiring.package=cucumber.runtime)(version>=2.0.0)(!(version>=3.0.0))) [caused by: Unable to resolve io.cucumber.core [18](R 18.0): missing requirement [io.cucumber.core [18](R 18.0)] osgi.wiring.package; (osgi.wiring.package=io.cucumber.tagexpressions)] Unresolved requirements: [[io.cucumber.osgi [20](R 20.0)] osgi.wiring.package; (&(osgi.wiring.package=cucumber.runtime)(version>=2.0.0)(!(version>=3.0.0)))])
org.osgi.framework.BundleException: Unable to resolve io.cucumber.osgi [20](R 20.0): missing requirement [io.cucumber.osgi [20](R 20.0)] osgi.wiring.package; (&(osgi.wiring.package=cucumber.runtime)(version>=2.0.0)(!(version>=3.0.0))) [caused by: Unable to resolve io.cucumber.core [18](R 18.0): missing requirement [io.cucumber.core [18](R 18.0)] osgi.wiring.package; (osgi.wiring.package=io.cucumber.tagexpressions)] Unresolved requirements: [[io.cucumber.osgi [20](R 20.0)] osgi.wiring.package; (&(osgi.wiring.package=cucumber.runtime)(version>=2.0.0)(!(version>=3.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
```

Not sure what caused this though.

**Comment by brasmusson** [comment]
The failure in the `pax-exam` example is because the tag-expression library is not built as an (OSGi) bundle. Merging https://github.com/cucumber/cucumber/pull/99 fixes that problem.

**Comment by aslakhellesoy** [comment]
Thanks @brasmusson - feel free to merge that one. In fact, feel free to merge anything you like!

**Comment by mattwynne** [comment]
@brasmusson I merged cucumber/cucumber#99 but is that enough? Does it need to be released too? Do we need to reference the new version somehow from this package?

**Comment by brasmusson** [comment]
@mattwynne The [pom.xml](https://github.com/cucumber/cucumber-jvm/blob/master/pom.xml#L77) specifies the version of the dependencies, and for the tag-expression library it specifies the latest released version (1.0.0). When this version is updated to point to a version that contains cucumber/cucumber#99, the build will start to pass again. Unlike Cucumber-JVM itself, the tag-expression library is not set up to deploy the latest content on the master branch to the [Sonatype snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/), so a new release of the tag-expression library is needed.

**Comment by mattwynne** [comment]
Who can make releases of `tag-expressions` @brasmusson? Does that have to be @aslakhellesoy or can you do it?

**Comment by aslakhellesoy** [comment]
I've released `tag-expressions` 1.0.1

**Comment by mattwynne** [comment]
Nice one @aslakhellesoy! 👍

**Comment by brasmusson** [comment]
As far as I can see the "remove wicket" is not necessary. I'll bring in the bump to tag-expressions v1.0.1 to master when I come home (if no else has done it then).

**Comment by mattwynne** [comment]
> I'll bring in the bump to tag-expressions v1.0.1 to master when I come home (if no else has done it then).

If you do that (and it fixes the build) we can just close this ticket.

**Comment by brasmusson** [comment]
Now the build is green - with [`Bump tag-expressions to 1.0.1 (supports OSGi)`](https://github.com/cucumber/cucumber-jvm/commit/177cc3a4d83fbee77b1fa695b506f02c73e61aee) on the master branch.

**Comment by mattwynne** [comment]
> Now the build is green

\o/ Good work team!

**Comment by aslakhellesoy** [comment]
Great! So let's revert the commit that removed wicket if that wasn't necessary before merging this.

**Pull request closed without merging**
