### PR TITLE
Get Feature Information from Scenario

### PR DESCRIPTION
**Pull request by corinned**
Use @Before with a call to getFeature() on the Scenario object to get the instance of the Feature.  Use the Feature instance to get information about the Feature for logging.

public void get_feature_name(Scenario scenario) {
     Feature feature = scenario.getFeature();
     featureName = feature.getName();
     tags = feature.getSourceTagNames();
}
#902

### CODE REVIEW

**Comment by Purus** [comment]
+1

**Comment by kirillzh** [comment]
Would be a great feature to have!

**Comment by b-lal** [comment]
Hi,
I was actually looking for this functionality, great idea Corinne.
When this is due to be release?

**Comment by brasmusson** [comment]
When upgrading Cucumber-JVM to use Gherkin v4.0.0 with the new [Gherkin compiler](https://github.com/cucumber/gherkin#compiler) (which is where I focus my effort currently), the Feature information will not be available when running compiled scenarios. So @b-lal, my answer would be that this PR will not be merged (I'm sorry @corinned).

**Comment by aldosuwandi** [comment]
+1

**Comment by brasmusson** [comment]
Now that the master branch as been updated to use Gherkin v4, this pull-request has been invalidated - and it is not possible to provide the feature name to Before or After Hooks (see [this comment](https://github.com/cucumber/cucumber-jvm/issues/902#issuecomment-309293480)).

**Comment by nsidhaye** [comment]
Hmm. Want to run cleanups after feature file. :(

**Pull request closed without merging**
