### PR TITLE
Use gherkin4 review nitpicks

### PR DESCRIPTION
**Pull request by mpkorstanje**
Lets try #1122 again.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Owh the its are under a separate profile. Oops.

**Comment by mpkorstanje** [comment]
@aslakhellesoy and @mattwynne build is green again except for open-jdk-7.

Reverted making Match package private. This made JSONFormatterTest fail because mockito was no longer able to mock on the remote server. Unsure why it works locally.

Also removed the fix for the EnumResult status because this will be properly solved in #1133.

**Comment by brasmusson** [comment]
The class TestNGCucumberRunner needs to be public for the use cases where the runner class does not inherit from AbstractTestNGCucumberTests, see https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-calculator-testng. I have fixed that.

**Comment by brasmusson** [comment]
Merged in ac1b214.

**Pull request closed without merging**
