### PR TITLE
[Examples] Fix java webbit websockets selenium

### LINKED ISSUE #1033: Could not initialize class SharedDriver
I'm trying to run the github.com/cucumber/cucumber-jvm/tree/master/examples/java-webbit-websockets-selenium on my Mac (10.11.6) doing `mvn install`, but I get the error `Could not initialize class cucumber.examples.java.websockets.SharedDriver`. A Firefox window comes up, but closes after some time (55.393 s). The last thing I tried was installing the new geckodriver v0.9.0 from github.com/mozilla/geckodriver/releases, but I get the same error. (I'm not sure where to put the DesiredCapabilities for this geckodriver.) My Java version is 1.8.0_66.
If there is no easy fix for this example, then I would be glad to be directed to some other simple Cucumber-JVM-web example (Scala-Play-sbt if possible).

Here the final part from the console:

```
Scenario: 100 Fahrenheit to Celcius  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class cucumber.examples.java.websockets.SharedDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
    at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
    at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
    at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
    at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
    at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
    at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
    at cucumber.runtime.java.picocontainer.PicoFactory.getInstance(PicoFactory.java:37)
    at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
    at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
    at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
    at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
    at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
    at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
    at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
    at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
    at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Tests in error: 
  null
  Could not initialize class cucumber.examples.java.websockets.SharedDriver
  Could not initialize class cucumber.examples.java.websockets.SharedDriver
  Could not initialize class cucumber.examples.java.websockets.SharedDriver
  Could not initialize class cucumber.examples.java.websockets.SharedDriver
  Could not initialize class cucumber.examples.java.websockets.SharedDriver

Tests run: 15, Failures: 0, Errors: 6, Skipped: 9

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.156 s
[INFO] Finished at: 2016-08-01T09:38:33+02:00
[INFO] Final Memory: 13M/143M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project java-webbit-websockets-selenium: There are test failures.
[ERROR] 
[ERROR] Please refer to /Volumes/P3/Cucumber/cucumber-jvm/examples/java-webbit-websockets-selenium/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### PR DESCRIPTION
**Pull request by mpkorstanje**
Updated dependencies and added spiffy new webdriver factory that  in
 combination with the driver-binary-downloader-maven-plugin just works.

 Related issues:
  - #1033

This fixes #1033

### CODE REVIEW

**Comment by mpkorstanje** [comment]
This is weird:

Oracle 7 passes: https://travis-ci.org/cucumber/cucumber-jvm/jobs/244287153/config
OpenJdk 7 fails: https://travis-ci.org/cucumber/cucumber-jvm/jobs/244287152

Reason: java.lang.UnsupportedClassVersionError: org/openqa/selenium/WebDriver : Unsupported major.minor version 52.0

Neither should support java 8.

**Comment by brasmusson** [comment]
The examples are only executed on OpenJDK7, so it is not weird that OracleJDK7 passes. The original reason not to execute the examples on OracleJDK7 was so that they should not be deployed to the snapshot repo, which is done from the OracleJDK7 job (except from the java8 module which is deployed from the OracleJDK8 job).

**Comment by mpkorstanje** [comment]
We should probably use the skip attribute.

http://maven.apache.org/plugins/maven-deploy-plugin/faq.html#skip

**Comment by brasmusson** [comment]
Now that we have moved the snapshot deploy to `after_success`, I think it would be possible to execute the examples in all Travis builds, and only do the snapshot deploy after also the examples have passed. If some examples only should execute on Java8, yes we could use the skip attribute.

**Comment by brasmusson** [comment]
If the `java-webbit-websockets-selenium` example cannot be built on Java7, it should probably be moved out of the `examples` profile to an `java8-examples` profile (similar to the [`android-examples`](https://github.com/cucumber/cucumber-jvm/blob/master/pom.xml#L598-L603) profile), so that the `examples` profile can be used on Java7.

**Comment by mpkorstanje** [comment]
I've given this some thought. The current PR is not quite where I want it to be yet. 

I've written down the way I'd like to set things up below. It is a bit of a short hand so I hope you don't mind too much.

```
pom.xml : sets source and target level to 1.6 for everything.
 - instance of a java7 module
 - instance of a java7 module
 - instance of a java7 module
 - instance of a java8 module: enabled by java8 profile in pom.xml override source and target level to 1.8
 - instance of an android module: enabled by android profile in pom
 - examples module: sets skip-deploy for all child modules
   - instance of a java 7 module with examples
   - instance of a java 7 module with examples
   - instance of a java 7 module with examples
   - instance of a java 8 module: enabled by java8 profile in examples module override source and target level to 1.8
   - instance of an android module with examples: enabled by android profile in pom
```

```
build: 
  - openjdk7: test and build everything that can be build on java 7
  - oraclejdk7: test and build everything that can be build on java 7
  - oraclejdk8: test and build everything 

after all builds pass:
  - oraclejdk8: build and deploy everything
```

The advantage of this setup is that we only need a java8 profile and an android profile. All examples are skipped from deployment because they're part of the examples module which uses the pluginManagement section to configure the deployment plugin of all submodules. 

Additionally by doing a release only java8 we don't need to specify which modules to release. The modules themselves will be compiled down to 1.6 unless otherwise specified.

I believe this removes some oddities in the current build and should make it easier to setup future integration tests with android.

**Pull request merged**
