### PR TITLE
[Core] Refactor Runtime

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Summary

Extracting:
 * Backend creation, 
 * Glue creation,  
 * Runner creation
 * Feature compilation 

from the runtime allows  
 * Tests on runners to skip the creation of Runtime
 * Makes extracting Filter provider(#1352) and  Feature provider(#1366) easier.
 * Will allow other runtimes such as JUnit and TestNg  to skip the creation of the runtime
 * Will facilitate parallel (#1357), junit 5 (#1149) and  pickle runner support.
 * Clarifies the execution loop of Cucumber

### CODE REVIEW

**Comment by boaty82** [comment]
Pulled the branch to work on some changes for [PR 1357](https://github.com/cucumber/cucumber-jvm/pull/1357) and before I've made any changes I'm running the tests (whilst perusing the changes already made for me) and I get the following issue

```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.10.2:check (check) on project cucumber-java: The following API problems caused the build to fail:
[ERROR] java.annotation.noLongerPresent: @interface cucumber.api.java.ht.SipozeKe: Old API referenced the annotation type but the new API version no longer does. (breaks semantic versioning)
[ERROR] java.annotation.noLongerPresent: @interface cucumber.api.java.ht.SipozeKe: Old API referenced the annotation type but the new API version no longer does. (breaks semantic versioning)
[ERROR]
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR] "code": "java.annotation.noLongerPresent",
[ERROR] "old": "@interface cucumber.api.java.ht.SipozeKe",
[ERROR] "package": "cucumber.api.java.ht",
[ERROR] "classQualifiedName": "cucumber.api.java.ht.SipozeKe",
[ERROR] "classSimpleName": "SipozeKe",
[ERROR] "elementKind": "@interface",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] },
...
```

**Comment by mpkorstanje** [comment]
Hey, feel free to comment out the revapi plugin. If you comment out the one
in the plugins section, not the plugin management section it should be
easy.

Not sure what is causing this. Looks like the languages aren't generated.

**Comment by boaty82** [comment]
I’ve done that. Just thought there might be a more “proper” fix

**Comment by mpkorstanje** [comment]
No. Don't have a solution yet. There is something going wrong when you run the build. Maybe something executed in the wrong order that causes the languages not to be generated.

**Comment by mpkorstanje** [comment]
I've moved the semantic version check to a different profile. This slows down the feedback loop a bit, but this is okay because we'll figure out which version it has to go in when merging. Not when building the feature.

**Comment by mpkorstanje** [comment]
Also feel free to ignore any problems with `pax-exam`.

**Comment by boaty82** [comment]
I've found a nice solution.

I've created a new event `TimerEvent`, which `StepDurationTimeService` now registers for. 
 Updated `TestStepStarted` to implement it

I then had to update `EventBus` to loop through the handler map and check if the incoming event is an instance of the class in the key, rather than getting the key.

**Comment by mpkorstanje** [comment]
Hey Boaty,

I'd rather not introduce a new event. I don't think it is needed.

The current tests for the formatters are setup such that cucumber generates
a stream of events. For tests we mock the time service so we can tick the
clock manually and get predictable timestamps.

The generation of these events is currently closely tied to the rest of the
implementation and the tests. This was okay in the past. There was only one
ordering of events. Now we have multiple orderings to deal with.

Generating these in a controlled fashion requires first that we make the
concept of an event stream explicit.

An event stream is a sequence of events with some ordering:

[TestStarted, TestSourceRead, {[ScenarioStarted, Step1, Step2,
ScenarioFinished]*}, TestFinished]

[This is in order], {these can come in any order}, these* can repeat.

So by recording a regular event stream and shuffling the groups of scenario
events we can simulate the result of a concurrent execution.

This might also make the implementation of formatters simpler. Rather then
trying to make all the formatters smart, we can record the events and
replay them in the right order (sort the groups of scenario events by uri).

-MP

PS: Can't look at the code. On a boat.

**Comment by boaty82** [comment]
Hi.

Haven't needed to add a new event interface in the end.  Managed to just create a new EventBus implementation now, purely for tests, so `TestStepStarted` events are sent for only certain `EventListener`s - in my case `StepDurationTimeService`

Have done the changes to support `--threads`, just adding the thread timeline report now.  Do the HTML/JS/etc files need to go in a new jar & repo link the HTML plugin?  I won't have permission to do this

**Pull request merged**
