### PR TITLE
Add Sha256sum to validate the maven binary used for the building the project

### PR DESCRIPTION
**Pull request by bmscomp**
### 🤔 What's changed?
No breaking changes and brought over this pull request, the only thing is adding an entry on the `maven-wrapper.properties `  `distributionSha256Sum` 

### ⚡️ What's your motivation? 
To be able to validate the content of the downloaded binary with a given sha256sum and to be sure that nothing is missing or it or not corrupted

### 🏷️ What kind of change is this?
It's about adding a new entry for `distributionSha256Sum` on `maven-wrapper.properties`

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
- :bug: Bug fix (non-breaking change which fixes a defect)
- :zap: New feature (non-breaking change which adds new behaviour)
- :boom: Breaking change (incompatible changes to the API)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Cheers. Could you also add the `wrapperSha256Sum`?

**Comment by bmscomp** [comment]
@mpkorstanje  I'll give it and try and check the ci after that

**Comment by bmscomp** [comment]
@mpkorstanje I think there is an issue with the maven wrapper validation in Maven, better to roll back the last change the time that will be fixed on maven

**Comment by mpkorstanje** [comment]
Where did you find the hash for `maven-wrapper.jar`?

**Comment by mpkorstanje** [comment]
Ah. No, nevermind. It is the Windows builds that fail.

**Comment by bmscomp** [comment]
@mpkorstanje it's the failure is related to windows build, it can be an issue of maven on windows or an issue of github actions when it comes to use a windows operating system to build

**Comment by mpkorstanje** [comment]
Reading these two

 * https://github.com/actions/runner-images/issues/225
 * https://github.com/PowerShell/PowerShell/issues/18108
 
It looks like Powershel broke it.

**Comment by mpkorstanje** [comment]
Good enough for now. Cheers!

**Pull request merged**
