### PR TITLE
[Core] Add property based variant for each runtime option

### LINKED ISSUE #1675: Provide a property name variant for each runtime option
## Summary

It is possible to pass properties to cucumber using CLI arguments in a property. E.g.

```
mvn clean test -Dcucumber.options="--strict --monochrome"
``` 
This is rather complicate, esp when multiple layers are involved and qoutes get confusing (e.x: https://github.com/cucumber/cucumber-jvm/issues/1596). 

```
mvn clean test -Dcucumber.options='--strict --monochrome --tags "not @ignored"'
``` 

A better way to do this would be to provide each option individually:

```
mvn clean test -Dcucumber.strict=true -Dcucumber.monochrome=true -Dcucumber.tags="not @ignored"
```

Once this is available we deprecate `cucumber.options`.

## Possible Solution

In `develop-v5` the `CucumberPropertiesParser.parse` method is provided with a map containing  properties from either either a `cucumber.properties` file, environment variables, or system properties.

After parsing `cucumber.options` an options builder is created. When a property is present the builder can be used to set the matching option to the right value.

Supported properties:
```
cucumber.glue=<separated list of paths>  #using OS appropriate seperator
cucumber.features=<separated list of paths>   #using OS appropriate seperator
cucumber.tags=<single tag expression>
cucumber.name=<regex>
cucumber.ansi-colors.disabled=<boolean>
cucumber.execution.dry-run=<boolean>
cucumber.execution.strict=<boolean>
cucumber.execution.parallel.config.fixed.parallelism=<int>
cucumber.execution.limit=<positive integer>
cucumber.execution.order=<reverse|random|random:seed>
cucumber.snippet-type=<underscore|camelcase>
cucumber.wip=<boolean>
```

Property names where possible should match those used by JUnit 5: https://github.com/cucumber/cucumber-jvm/blob/junit-jupiter/junit-platform-engine/src/main/java/io/cucucumber/jupiter/engine/Constants.java

To document this properly with Java doc please take hints from:

https://junit.org/junit5/docs/current/api/constant-values.html
https://junit.org/junit5/docs/current/api/org/junit/jupiter/engine/Constants.html

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Summary

Adds properties for all CLI options. Removes the ability to load rerun files from the class-path. There appears to be no use case and it significantly simplifies the implementation.

## Details

Adds:

```
cucumber.ansi-colors.disabled
cucumber.execution.dry-run
cucumber.execution.limit
cucumber.execution.order
cucumber.execution.parallel.config.fixed.parallelism
cucumber.execution.strict
cucumber.execution.wip
cucumber.feature
cucumber.rerun-file
cucumber.filter.name
cucumber.filter.tags
cucumber.glue
cucumber.object-factory
cucumber.plugin
cucumber.snippet-type
```

## Motivation and Context

It is possible to pass properties to cucumber using CLI arguments in a property. E.g.

```
mvn clean test -Dcucumber.options="--strict --monochrome"
``` 
This is rather complicate, esp when multiple layers are involved and quotes get confusing (e.x: https://github.com/cucumber/cucumber-jvm/issues/1596). 

```
mvn clean test -Dcucumber.options='--strict --monochrome --tags "not @ignored"'
``` 

A better way to do this would be to provide each option individually:

```
mvn clean test -Dcucumber.strict=true -Dcucumber.ansi-colors.disabled=true -Dcucumber.filter.tags="not @ignored"
```

Closes #1675

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [X] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
The `rerun-file` and `glue-file` options don't work well at all. Properties are single values. They don't work well at all with maps and the semantics of combining them are messy.

Best to leave them out for now and revisit them once the JUnit 5 implementation comes along.

**Comment by mpkorstanje** [comment]
Looks like the common practice is to use comma separated lists and use strict overriding. Which is exactly what we do right now.

A complicating factor is that JUnit and TestNG will always override `cucumber.glue` and `cucumber.features` with the package of the runner. But from a hierarchical perspective that makes sense.

**Comment by salunkhe-ravi** [comment]
For some reason "cucumber.execution.limit=1" doesn't work for me...
Can anyone share me some examples and/or usage documentation please?

**Comment by mpkorstanje** [comment]
Not all runners support all options. Limit is only supported by the CLI.

**Pull request merged**
