### PR TITLE
[Core] Default to --strict mode

### PR DESCRIPTION
**Pull request by mpkorstanje**
Unlike other implementations Cucumber-JVM defaults to `--non-strict` mode. By defaulting to `--strict` Cucumber follows the same standards as other implementations.

Additionally the option to set strict mode adds complexity for consumers of Cucumbers output. They have to interpret Cucumbers 6 scenario outcomes with this in mind. By removing `--strict/--non-strict` mode we remove this complexity all together.

With PR Cucumber will:
 * default to `--strict` 
 * throw an error on `--non-strict`.  
 * warn when `--strict` is used.
 * only print snippets as part of the exception thrown by JUnit rather then use the summary printer
 * only print snippets as part of the exception thrown by TestNG rather then use  the summary printer

Partial fix for #1788, https://github.com/cucumber/cucumber/issues/714

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [X] I've added tests for my code.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sebrose** [comment]
The title of this PR (and the comment in the Changelog) imply only a change of default. It looks like the whole idea of non-strict has been removed. 

Am I missing something?

**Comment by mpkorstanje** [comment]
Internally the implementation is gone. However we're still in the process of phasing out the user facing part.

https://github.com/cucumber/cucumber-jvm/blob/d3f795686afbee0d633baa71b27539ebbc6e15ee/core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java#L137-L142

**Comment by Colin-Heyl** [comment]
Hi, wondering if someone can verify something for me?

We're using Cucumber at the moment and a test will **not** fail, if a feature is not found. 

Shouldn't that happen if strict mode is now the default? Or has strict functionality just been stripped out for some reason?

**Comment by mpkorstanje** [comment]
Strict mode only affects translating PENDING, UNDEFINED, AMBIGUOUS steps results into a pass or fail. It does not do anything w.r.t to features being discovered.

If you have a feature request, please create a new issue though.

**Pull request merged**
