### PR TITLE
Enable reproducible builds

### PR DESCRIPTION
**Pull request by hboutemy**
### 🤔 What's changed?

see https://maven.apache.org/guides/mini/guide-reproducible-builds.html

### ⚡️ What's your motivation? 

Reproducible Builds

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Hey thanks for wanting to help out!

Did you also test the reproducibility? We have some custom code generation and because support for modules in Maven is still very janky `mvn clean verify` doesn't work. So I'm a bit puzzled about that.

It would also be nice if we could add this to CI to ensure we don't break it in the future.

**Comment by hboutemy** [comment]
> Did you also test the reproducibility?

I tested the reproducibility by running:
```
mvn clean install && mvn clean verify artifact:compare
```
which is the first level of tests = 2 local builds

> It would also be nice if we could add this to CI to ensure we don't break it in the future.

Reproducible Builds will be tested on future releases by https://github.com/jvm-repo-rebuild/reproducible-central

**Review by mpkorstanje — APPROVED** [review]
Looks good.

I've included [the plugin version changes in `cucumber-parent` instead](https://github.com/cucumber/cucumber-parent/compare/v3.0.0...v4.0.2). This should avoid the need to manually set versions in this project.

The build will eventually pass once `cucumber-parent` arrives on Maven Central.

Do note that Cucumber-JVM depends on several components that are build elsewhere in the Cucumber org. These include:

* https://github.com/cucumber/tag-expressions
* https://github.com/cucumber/messages/
* https://github.com/cucumber/cucumber-expressions/
* https://github.com/cucumber/html-formatter
* https://github.com/cucumber/ci-environment
* https://github.com/cucumber/gherkin

Will you also make these reproducible?

**Comment by aslakhellesoy** [comment]
Hi @hboutemy,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
