### PR TITLE
[Junit Platform] Deprecate @Cucumber in favour of @Suite

### PR DESCRIPTION
**Pull request by mpkorstanje**
The CucumberJUnit Platform Engine has been updated to 1.8. With JUnit 5.8 comes 
the `junit-platform-suite` engine. This engine allows the 
[programmatic declaration of test suites](https://junit.org/junit5/docs/current/user-guide/#test-suite).

So it is now possible to write the following JUnit 4 test:

```java
package com.example;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(glue = "com.example.application", features = "classpath:com/example/application")
public class RunCucumberTest {

}
```

As a declarative JUnit 5 test suite: 

```java
package com.example;

import org.junit.platform.suite.api.ConfigurationParameter;
import org.junit.platform.suite.api.IncludeEngines;
import org.junit.platform.suite.api.SelectClasspathResource;
import org.junit.platform.suite.api.Suite;

import static io.cucumber.junit.platform.engine.Constants.GLUE_PROPERTY_NAME;

@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("com/example/application")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example.application")
public class RunCucumberTest {

}
```

In combination with the before-all and after-all hooks this allows for a
feature-complete migration from JUnit 4. And allows us to deprecate
the `@Cucumber` annotation in favour of `@Suite`.

Fixes: #2331

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Waiting for JUnit 5.8 to be available.

**Comment by aslakhellesoy** [comment]
This sounds great! When something is deprecated I think docs should etc should document the new way rather than the old. 

We need a ticket to keep track of what needs to be updated. Quick brain dump:

- docs repo
- skeleton repo
- archetype repo
- this repo (in case @Cucumber is still ised)

**Comment by mpkorstanje** [comment]
The `@Cucumber` annotation was never documented outside this repository. It was a workaround to get Cucumber going with JUnit5 and Surefire/Gradle.

We _can_ replace JUnit 4 with JUnit 5 now in the docs.cucumber.io though.

> archetype repo

Part of this repo. Already covered.

> skeleton repo

https://github.com/cucumber/cucumber-java-skeleton/pull/64/files

> docs repo

Only thing left to do.

**Comment by davidghiurco** [comment]
> package com.example;

  import org.junit.platform.suite.api.ConfigurationParameter;
  import org.junit.platform.suite.api.IncludeEngines;
  import org.junit.platform.suite.api.SelectClasspathResource;
  import org.junit.platform.suite.api.Suite;
  
  import static io.cucumber.junit.platform.engine.Constants.GLUE_PROPERTY_NAME;
  
  @Suite
  @IncludeEngines("cucumber")
  @SelectClasspathResource("com/example/application")
  @ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example.application")
  public class RunCucumberTest {
  
  }
  
@mpkorstanje For my use-case, I need to be able to run `RunCucumberTest` class from a "fat-jar" (created using `maven-shade-plugin`). The plugin *requires* a main method be specified:

`
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                                <configuration>
                                    <shadedArtifactAttached>true</shadedArtifactAttached>
                                    <shadedClassifierName>jar-with-dependencies</shadedClassifierName>
                                    <createDependencyReducedPom>false</createDependencyReducedPom>
                                    <transformers>
                                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                            <mainClass>com.my.company.package.RunCucumberTest</mainClass>
                                        </transformer>
                                    </transformers>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
`

Linking the class name `RunCucumberTest` (as you currently wrote it) as the main method class to `maven-shade-plugin`, compiling the fat jar, and trying to run it will yield a "Main method not present or cannot be found" error at runtime.

Including an empty main method within class `RunCucumberTest`:
`
public final class RunCucumberTest {
    public static void main(String[] args) {}
}
`
will do nothing when run from the fat-jar (for obvious reasons). 

Back in JUnit 4 platform, my solution to this was:

`
import org.junit.runner.JUnitCore;
...
public final class RunCucumberTest {
    public static void main(String[] args) {
        JUnitCore.main(ProductAcceptanceTests.class.getName());
    }
}
`

What is the correct JUnit 5 `main()` invocation?

**Comment by mpkorstanje** [comment]
The JUnit 5 equivalent of `JUnitCore.main` is the JUnit Platform Console Launcher. 

https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher

Cucumber also has a main method of it's own: `io.cucumber.core.cli.Main`.

**Comment by davidghiurco** [comment]
> Cucumber also has a main method of it's own: io.cucumber.core.cli.Main.

This seems to work:

```java
import io.cucumber.core.cli.Main;
...
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("com/my/company/package/features")
@ConfigurationParameters({
    @ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "pretty"),
    @ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "html:target/report/cucumber.html"),
    @ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "json:target/report/cucumber.json"),
    @ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "junit:target/report/cucumber.xml"),
    @ConfigurationParameter(key = FILTER_TAGS_PROPERTY_NAME, value = "not @Ignore"),
    @ConfigurationParameter(key = PLUGIN_PUBLISH_QUIET_PROPERTY_NAME, value = "true")
})
public final class RunCucumberTest {
    public static void main(String... args) {
        Main.main();
    }
}
```

However, if `main()` is called with no parameters, the @ConfigurationParameters array isn't taken into account, and I lose that configuration when running from fat-jar.

Is there a way to pass a reference to the `RunCucumberTest` class so that its configuration is taken into account? 

That's what was happening when calling `JUnitCore.main(RunCucumberTest.class.getName());`

**Comment by mpkorstanje** [comment]
Either you run Cucumber directly through it's own main method. Or you run Cucumber through JUnit 5.

If you run Cucumber directly, any instructions for JUnit related to running Cucumber will be ignored. If you run Cucumber directly you don't need and can remove any and all parts related to JUnit 5 from your project.

If you do run Cucumber through JUnit 5 and you want to run JUnit 5 from a main method you have to use the Console Launcher provided by JUnit 5.

**Pull request merged**
