### PR TITLE
Add afterStep hook to cucumber-java and plugins

### PR DESCRIPTION
**Pull request by heldev**

### CODE REVIEW

**Comment by Evg3n** [comment]
Hi heldev,

I also worked on this a year ago, but for some reason my pull request has been ignored after I fixed all I was asked to. Not sure why. You can refer to it https://github.com/cucumber/cucumber-jvm/pull/838.

A lot of people are asking about it...but still no answer.

Best regards,
Evg3n.

**Comment by heldev** [comment]
Hi @Evg3n ,

I saw you PR but at that time I just decided that it was abandoned and also authors wanted implementation with changes in reporting API  https://github.com/cucumber/cucumber-jvm/issues/604#issuecomment-26166441 - here. Now I see that it was my mistake :)

BTW I'm wondered why you need step hooks ?
E.g. in my case I would like to check a browser console for JS errors and warning after each step.

**Comment by ali-himindz** [comment]
Are we getting this PR merged soon? thanks if you are doing it soon :).

**Comment by mpkorstanje** [comment]
The reason this has not yet been merged from #604:

> Speaking for me personally, I'm focusing the time I have available to work on upgrading Cucumber-JVM to use Gherkin v4.0.0. From that perspective I would not want to add step hooks before there is an Cucumber-JVM v2.0.0-SNAPSHOT available that uses Gherkin v4.0.0.

As we're currently approaching a 2.0.0 release. This feature won't make it into that one but if this PR rebased or rewritten against the current master I'll see it merged.

**Comment by G0dwin** [comment]
> BTW I'm wondered why you need step hooks ?

@heldev, we need this feature because we would like to take screenshots and HTML captures after each step so that we can produce better error reports.

**Comment by snargleplax** [comment]
I'm watching this PR because I have a use case as well; I have some fixture steps that require a coordinating trigger to "activate" them once they've all been specified. Would love to see this merged at some point. Currently I have to rely on conventions and a special step that hits the trigger; it works, but it's limited and brittle.

**Comment by brasmusson** [comment]
@heldev @Evg3n @G0dwin @snargleplax Note that the implementation of AfterStep hooks in this PR is base on the old Gherkin v2 design of Cucumber-JVM, with the upgrade to Gherkin v4 this implementation has been invalidated. It is not just a matter of rebasing this PR, it requires a complete new implementation based on the [TestCase from Pickle creation](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runner/Runner.java#L93-L103), so currently there is no implementation of AfterStep hooks that could even be considered to be merged.

**Comment by csnthsh120** [comment]
When is this hook is going to be available???

**Comment by coding-yogi** [comment]
@mpkorstanje , I have kind of implemented the AfterStep hook and it works fine from functionality perspective but messes up HTML report. Anything after "AfterStep" hook is not getting written to HTML report but Junit reports are coming up fine. Although I am already debugging, any pointers would be helpful?

**Comment by coding-yogi** [comment]
I had to add "afterstep" method here -> https://github.com/cucumber/cucumber-html/blob/master/src/main/resources/cucumber/formatter/formatter.js . 

Works fine now

**Comment by mpkorstanje** [comment]
Cool. Can you provide both as a PR so we can review.

**Comment by coding-yogi** [comment]
I am yet to write some tests. But if you wish to have a quick look --> https://github.com/coding-yogi/cucumber-jvm/commit/783828d8583525387d751e093f8e713217e1001a

**Comment by mpkorstanje** [comment]
Superceded by  #1323.

**Comment by BhuvaneshMani** [comment]
@coding-yogi Has this been already rolled out? Was waiting for longtime to get this feature. If yes, let me know which version to use from maven central.

**Pull request closed without merging**
