### PR TITLE
WIP: Use Gherkin 6 / Remove rich formatters.

### PR DESCRIPTION
**Pull request by aslakhellesoy**
Removed JSON/HTML/Pretty/JUnit XML formatters and related cruft.

See:
* https://github.com/cucumber/cucumber/pull/416
* https://github.com/cucumber/cucumber/issues/415

This is a big change, and it may conflict with #1389.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Had a quick look. I am seeing allot of changes in imports that only seem to change the order.

**Comment by aslakhellesoy** [comment]
Is that going to be a problem? I use IDEA optimise imports a lot.

**Comment by mpkorstanje** [comment]
Merge conflicts I imagine. We could run optimize imports on both branches though and hope it works out though.

**Comment by aslakhellesoy** [comment]
This branch is stale, but let's keep it around. It's useful to look at some of the changes when we give this another try.

**Pull request closed without merging**
