### PR TITLE
Cucumber is ready to run in OSGi containers

### PR DESCRIPTION
**Pull request by HendrikSP**
This is an upgraded version of pull request of #799 

My changes include:

* Adds OSGi headers to core, java and JUnit bundles.
* Changed loading of the USAGE.txt in RuntimeOptions, because due to OSGi class loading cause problems. I wrote more details in the commit message.
* Pax Exam example is included.

*NOTE*: Please release cucumber-jvm-deps with my other pull request (see https://github.com/cucumber/cucumber-jvm-deps/pull/3), because this changes make only sense when the jvm-deps bundle has also OSGi headers.

Thank you!

### CODE REVIEW

**Comment by dkowis** [comment]
Why does it need the snapshot version of cucumber-jvm-deps? And we should probably have this depend on a release of 1.0.4 of that. We cannot release with a snapshot dependency.

**Comment by dkowis** [comment]
Okay I merged cucumber/cucumber-jvm-deps#3, and as soon as I can figure out the right hoops to jump through to release that, you'll have a 1.0.4 with the OSGi Header, and we can make sure the travis builds succeed, and then we can merge this guy :D

**Comment by HendrikSP** [comment]
Hi David!

Any success on releasing the new deps version? I could update my branch to 1.0.4

If you need anything else, pls let me know.

Regards, Hendrik

**Comment by dkowis** [comment]
@aslakhellesoy I need to know how to sign the release for the cucumber-jvm-deps project (or if you just do it or whatev.)

**Comment by dkowis** [comment]
@HendrikSP A new deps version has been released, 1.0.5. If you update this and travis passes, we can merge it :)

**Comment by aslakhellesoy** [comment]
Yep - I'm working on it now :-)

**Pull request merged**
