### PR TITLE
Cucumber V5

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Summary

Development branch for v5. Mostly to keep my local artifacts properly versioned.

Closes:  #1448

Notable changes so far

 - New internal package structure
 - New API package structure
 - Java and Java 8 modules have been merged
 - Now compiled as java 8.
 - Supports automatic module names
 - Supports repeatable annotations (Given, Given, Given).
 - Deprecate `cucumber.api.cli.Main` infavour of `io.cucumber.core.api.cli.Main`.|
 - Removed deprecated tags.
 - Fixed DEFAULT_BEFORE_ORDER not being set to the same value as DEFAULT_AFTER_ORDER
- Backends are now loaded via ServiceLoaders. Indicated in `io.cucumber.core.backend.BackendProvider`
- ObjectFactories are loaded via ServerLoader indicated in `io.cucumber.core.backend.ObjectFactory`
- Any backend can now be created with an `ObjectFactory`
- Java annotation and lambda based step defintions are now handled by different backends
- Share single object factory between backends. Let Cucumber handle start/stop of object factory
- Language from feature file will be used unless explicitly set using the `TypeRegistryConfigurer`.
- Java supports annotation based parameter and data table types as well as default converters

After retiring Cucumber v4
- [x] Use Java 8s `Instant` and `Clock` in the event bus
- [ ] Replace find and filter loops with streaming equivalents
- [ ] Use lambdas for event handlers
- [ ] Migrate to JUnit 5
- [ ] Add docs for `cucumber.properties` to https://cucumber.io/docs/cucumber/configuration/
- [ ] Add `@FunctionalInterface` to `datatable` and `cucumber-expressions` parameters

### CODE REVIEW

**Comment by mpkorstanje** [comment]
> Now compiled as java 8.

Should use java Clock as time provider now.

**Comment by mleegwt** [comment]
@mpkorstanje This is turning into quite a bit of refactoring. I am quite new in this repo. Would you like me to assist a bit by fixing some Javadoc where I can? If so, any preferences where to start?

**Comment by mpkorstanje** [comment]
You'd be most welcome to! 

I think any improvements to java doc in `*.api` packages would be most beneficial as that is our public api. But if you want to look at the java doc errors that are causing the build to fail that good too: 

https://travis-ci.org/cucumber/cucumber-jvm/jobs/503566921#L4593

**Comment by mleegwt** [comment]
Sure. I’ll see what I can do in a limited amount of time.

**Comment by mpkorstanje** [comment]
Every bit helps.

**Comment by mpkorstanje** [comment]
> Do we need the junit-jupiter-engine also to run with JUnit 5? (I was looking into the difference between these two and found this

We're not yet running JUnit 5 tests. So we probably don't need the JUnit Jupiter API yet. You can try to remove it if you want.

We're cant switch to JUnit5  yet until we've retired Cucumber v4. Until then we have to be mindful of not introducing changes that would cause severe merge conflicts.

**Comment by gazler22** [comment]
>  Replace find and filter loops with streaming equivalents

I found some TODOs while going through the code for my PR to update the loops to streams/lambdas. Do u want me to go through them and update them ?

I already did update two from `FixJava `on my local.

**Comment by mpkorstanje** [comment]
Not yet. While v4 exists I would like to be able to merge changes from v4 into v5. This works well when the branches aren't too divergent. So for now it helps to only introduce changes that support the new features of v5. Once v4 has been retired you'd be most welcome though!

**Comment by gazler22** [comment]
Ok. I ll take a look at the Java doc to see if I can find anything to update/fix. 

If you need any  with the refractoring, etc I am  happy to help.

**Comment by mpkorstanje** [comment]
@gazler22 when #1594 is merged into `master` and `master` has been merged into `develop-v5` would you like to spend some time replacing `long timeStamp` with `Instant`, `TimeService` with `Clock` and `long duration` with `Duration`?

**Comment by gazler22** [comment]
> 
> 
> @gazler22 when #1594 is merged into `master` and `master` has been merged into `develop-v5` would you like to spend some time replacing `long timeStamp` with `Instant`, `TimeService` with `Clock` and `long duration` with `Duration`?

Sure, I ll take a look and update as i get the time. So we are basically getting rid of the TimeService class altogether. And updating all the references to direcly use Instant, Clock and Duration for their purposes. 
Please correct me if I'm wrong.

And you want me to work with the developv5 branch for this, correct?

**Comment by mpkorstanje** [comment]
> Sure, I ll take a look and update as i get the time. So we are basically getting rid of the TimeService class altogether. And updating all the references to direcly use Instant, Clock and Duration for their purposes.

That is correct. It may be that you'll have to create a subclass of clock in a few places (just as we do with `TimeService`. Also I haven't investigated this in detail so you may run into complications. But we'll have to see.

> And you want me to work with the developv5 branch for this, correct?

Yes. Please base of `develop-v5` and send a merge request.

**Comment by gazler22** [comment]
> 
> 
> Also I haven't investigated this in detail so you may run into complications. But we'll have to see.

No problem. We ll work on it as we go along.

> Yes. Please base of `develop-v5` and send a merge request.

Ok. I ll start working and raise a PR once the master is merged into v5.

**Comment by timtebeek** [comment]
@mpkorstanje did a few fixes here, as it turns out not all references to `isScenarioScoped` were removed; Also, the build currently fails on `CHECK_SEMANTIC_VERSION=true` as this branch has moved classes around; Shall we disable that check for the duration of this branch?

**Comment by mpkorstanje** [comment]
Not a bad idea. It didn't bother me but it doesn't help either.

**Pull request merged**
