### PR TITLE
Update to the newer, faster infrastructure

### PR DESCRIPTION
**Pull request by dkowis**
I'm pretty sure this will work just fine.

### CODE REVIEW

**Comment by dkowis** [comment]
Wow! This is way faster. 8 minutes instead of 30 minutes. MERGINATING.

**Comment by brasmusson** [comment]
Comparing the build time [before](https://travis-ci.org/cucumber/cucumber-jvm/builds/78228274) and [after](https://travis-ci.org/cucumber/cucumber-jvm/builds/78921368) shows that on jdk7 the build is indeed faster (~14 minutes versus ~8 minutes) with this change, but interestingly enough on jdk8 the build is slower (~4½ minutes versus 6½ minutes).

**Comment by dkowis** [comment]
Huh, I saw times that were like 30 minutes, not 14 minutes.... Probably lots of variance in there :(

**Comment by dkowis** [comment]
Eh, nope, I was looking at total time for all three runs, not the individual runs. Interesting.

**Pull request merged**
