### PR TITLE
#989 Lazy loading feature file and running (JUnit or TestNG Runner)

### PR DESCRIPTION
**Pull request by stanislav-antufeev**
Please take a look at my source code changes.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Why did you close the PR?

**Comment by stanislav-antufeev** [comment]
Sorry, I will reopen. I am newbie on GitHub.

**Comment by stanislav-antufeev** [comment]
@aslakhellesoy  Are you seeing my pull request ?

**Comment by stanislav-antufeev** [comment]
@aslakhellesoy 
Is it any estimate to review and merge if there is no any issues from you point of view ?

**Comment by dkowis** [comment]
I'm not familiar with TestNG, but all the tests pass. Could I get one more sign off from someone else maybe with experience with TestNG?

**Comment by stanislav-antufeev** [comment]
Guys, please verify my request. Generate JUnit runner classes for about 10000 feature files is not cool solution.

**Comment by brasmusson** [comment]
As far as I can see this PR only implements lazy loading of feature files when using the TestNG module of Cucumber-JVM (that is extending `cucumber.api.testng.AbstractTestNGLazyLoadCucumberTests`), and lazy loading is not possible when using the JUnit module (that is `cucumber.api.junit.Cucumber`) or when using the CLI (that is `cucumber.api.cli.Main`). So I find the title of the PR misleading.

I would be happier if it was possible to lazy load regardless of the which of the above mentioned run interfaces were used. Lazy loading should not be the default behaviour, but rather enabled by an option, I think.

This PR introduces new interface functions on Core module for the TestNG module to use (`RuntimeOptions.getgetCucumberFeaturesAsResources`), I get the feeling that they could make it more difficult to implement a more general lazy loading solution later. All in all, I am a little reluctant to accept the RP as is.

> Generate JUnit runner classes for about 10000 feature files is not cool solution.

Since it is possible to override the setting of the JUnit runner class from the command line (`-Dcucumber.options="<settings>"`), there would not be any need for more than JUnit runner class, it could be called several times to run different feature files.

**Comment by stanislav-antufeev** [comment]
@brasmusson I agreed with you it will be best way to implement through an option lazy loading of feature file regardless of using interface (CLI, JUnit, TestNG). I am extensively using JVM implementation of Cucumber, CLI implementation  cucumber.api.cli.Main does not provide the running feature file one by one (in term of lazy loading) because in cucumber.runtime.model.CucumberFeature:111 Runtime.java is loaded in one shot all given feature files(through tags, paths) and parsing them, populating in memory Cucumber feature instances.
Junit testing library, at lest till version 4 does not provide an interface for lazy loading of resources for test method. Only what I found is TestNG Framework has such ability to lazily loading resources for test method.
I can implement lazy loading for CLI implementation, but I am sure for JUnit it won't work.

**Comment by stanislav-antufeev** [comment]
I will close this pull request because the feature has been implemented not completely.

**Pull request closed without merging**
