### PR TITLE
[Core] Escape spaces in resource name

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Summary
`classpathResourceUri` used `URI.create` which assumes that the URI
to parse is a valid URI. This assumption doesnt hold when
transforming paths into URIs. Instead the URI constructor should be
used which does escaped reserved characters.

Closes #1872

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [X] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by PeretzNadav** [comment]
Thank you very much for your quick response :) 

5.1.1 or 5.2.0 ????

**Comment by mpkorstanje** [comment]
v5.1.1, only bug fixes in this one.

**Comment by PeretzNadav** [comment]
are you going to publish 5.1.1 today ???

**Comment by mpkorstanje** [comment]
It's been published for a while now. Looks like `search.maven.org` didn't update properly.

https://repo1.maven.org/maven2/io/cucumber/cucumber-java/5.1.1/

**Pull request merged**
