### PR TITLE
Use latest Gosu release

### PR DESCRIPTION
**Pull request by DPUkyle**
## Summary
Gosu language support has been broken for a while now; I had a PR to re-enable it (see https://github.com/cucumber/cucumber-jvm/pull/1086). At @mpkorstanje 's request I retested locally using Java 8 and the command `mvn -pl gosu test`; everything is fine.

I also bumped the Gosu release to the newest release version.

AFAICT, this is good-to-go with the caveat that Gosu _only_ supports Java 8 these days (I tweaked the maven profile so that Travis won't try to run Gosu using Java 7).

### CODE REVIEW

**Comment by DPUkyle** [comment]
Sorry, this is a duplicate of #1155 , though it does have one commit to bump the `gosu.version` property.

The failing tests on #1155 seem to be related to `java-webbit-websockets-selenium` examples.

**Comment by mpkorstanje** [comment]
Cheers. I'll patch it all up tomorrow.

**Comment by DPUkyle** [comment]
Thanks. I appreciate your support!

**Comment by mpkorstanje** [comment]
Sorry about the delay. Cuckenfest got in the way. I've manually updated the version in #1155.

**Pull request closed without merging**
