### PR TITLE
[Core ] Update jQuery from 1.8.2 to 3.4.1

### PR DESCRIPTION
**Pull request by clarkead**
## Summary

Updated jQuery from 1.8.2 to 3.4.1 to remediate the prototype pollution in jQuery prior to 3.4.0/

## Details

Updated the jQuery version and changed a call to removeAttr() to prop() to fix a deprecation warning from jQuery migrate.

Solution for jQuery.fn.removeAttr():
https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnremoveattr-no-longer-sets-boolean-properties

## Motivation and Context

Updates jQuery to a supported version of jQuery that is safer and won't cause security scanners to flag the library as vulnerable.

## How Has This Been Tested?

I've loaded it in a browser with and without jQuery migrate and remediated any issues discovered.  I've also run the build + tests to ensure nothing broke.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thanks a lot @clarkead! Good job with the manual testing and sorry we don't have any automated tests for this. (At some point we intend to migrate to the new [html-formatter](https://github.com/cucumber/cucumber/tree/master/html-formatter) which does have proper tests).

Let's try to get this into the next 5 RC @mpkorstanje

**Comment by aslakhellesoy** [comment]
Hi @clarkead,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mpkorstanje** [comment]
Done. Cheers.

I'll try and back port it to v4.x as well.

**Comment by clarkead** [comment]
Thank you for reviewing the PR and creating and maintaining the project!

**Pull request merged**
